version: '3.8'

services:
  cart:
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - ecommerce-net

  payment:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge
